# Generated by Django 6.0.1 on 2026-02-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0005_pagecourse_content'),
        ('eduzone', '0009_course_linked_page_alter_result_score_and_more'),
    ]

    operations = [
    ]
